# arguments for dataset
dataset: acdc
nclass: 4
crop_size: 256  
data_root: 
fx_data_root: 
epochs: 300  
batch_size: 8 
lr: 0.01
conf_thresh: 0.95

exp_dir: 
model_type: ddpm
model_path: NONE

dim:
  - 256
  - 256
  - 30
steps:
  - 50
  - 150
  - 250
blocks:
  - 2
  - 4
  - 6

model_num: 10
max_training: 30

training_number: 1
testing_number: 1

upsample_mode: bilinear
share_noise: true
input_activations: false

attention_resolutions:
  - 32
  - 16
  - 8
class_cond: False
diffusion_steps: 1000
dropout: 0.1
learn_sigma: True
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_res_blocks: 2
resblock_updown: True
use_fp16: True
use_scale_shift_norm: True
image_size: 256